### ISSUE TITLE
User | Develop | Data | Toon het soort vervoersmiddel in de "Ruwe Data" export

### ISSUE THREAD

**Issue by sklompm** [Stichting-CROW/dashboarddeelmobiliteit-app#149]
Als een gebruiker
Wil ik het soort vervoersmiddel (fiets, 25/45km scooter, auto etc) per trip in de Ruwe Data export (trip.csv) krijgen
Zodat ik onderscheid kan maken in trips per vervoermiddel en hier rapportages van kan maken

Momenteel bevat de Ruwe Data export (trip.csv) geen veldje voor het type vervoersmiddel (vroeger volgens mij "vehicle_type_id" genoemd in de export die wij kregen wanneer wij data aanvragen via email regelden).

Wens is om dit in de ruwe data export te stoppen zodat wij dit kunnen gebruiken voor onze rapportages.

**Comment by bartwr** [comment]
Op 31 januari j.l. is de modaliteit ook zichtbaar in de ruwe data export ( https://github.com/Stichting-CROW/dd-raw-data-exporter/commit/d1c944470fb9ef75a9d616a1bbd0b60eac11a383 , https://github.com/Stichting-CROW/dd-raw-data-exporter/commit/33d9f27ba853b8906bb3f67045e2be8d327005cd ).

Nogmaals dank voor je suggestie @sklompm ! Laat het ons weten bij andere feedback :-)
