### ISSUE TITLE
Toon data van meerdere plaatsen tegelijkertijd

### ISSUE THREAD

**Issue by bartwr** [Stichting-CROW/dashboarddeelmobiliteit-app#185]
Organisaties/contractpartners kunnen gekoppeld zijn aan meerdere datagebieden.

Een gebruiker die inlogt kan een plaats selecteren om de data te zien.

Mooier is het als in eerste instantie alle voertuigen van alle plaatsen in 1x laden, als er nog geen plaats is geselecteerd.

**Comment by bartwr** [comment]
DO: Controleer of de API voor ophalen van zones meerdere gm_codes accepteert.

I.e.: https://api.dashboarddeelmobiliteit.nl/dashboard-api/zones?gm_code=GM0197,GM0034

**Comment by sven4all** [comment]
Parameter municipalities=GM0599,GM0518 toegevoegd, gm_code is vanaf nu deprecated maar vorlopig nog wel te gebruiken.
