### ISSUE TITLE
https://mds.dashboarddeelmobiliteit.nl/geographies gives a server error

### ISSUE THREAD

**Issue by frankhommers** [Stichting-CROW/dashboarddeelmobiliteit-app#217]
This https://mds.dashboarddeelmobiliteit.nl/geographies used to return all geographies, however, now it gives a database error.

**Comment by sven4all** [comment]
This is resolved.

It's btw not the recommended way to receive this information. The expected access paterns are:

Receive microhubs or no_parking zones via (municipality can be added as well on these endpoints):
- https://mds.dashboarddeelmobiliteit.nl/stop
- https://mds.dashboarddeelmobiliteit.nl/policies 
- https://mds.dashboarddeelmobiliteit.nl/policies?municipality=GM0599
- https://mds.dashboarddeelmobiliteit.nl/stops?municipality=GM0599

And then lookup geographies that you didn't download before with:
- https://mds.dashboarddeelmobiliteit.nl/geographies/<geography_id>
- https://mds.dashboarddeelmobiliteit.nl/geographies/5a800164-1c9f-11ee-8219-8ed3b2364c4f
