### ISSUE TITLE
Publieke versie van het dashboard

### ISSUE THREAD

**Issue by bartwr** [Stichting-CROW/dashboarddeelmobiliteit-app#22]
Als je niet ingelogd bent, moet https://dashboarddeelmobiliteit.nl/ een overzicht tonen van alle live voertuigen. De tooltip geeft niet veel informatie, behalve:

- Naam aanbieder
- Type voertuig
- Website-URL aanbieder

Alle markers zijn donkergroen, met een bolletje erbij voor aanbieder.

Het filtermenu toont alleen relevante filters, zoals plaats, zones, voertuigtype en aanbieder.

**Comment by bartwr** [comment]
DO: Breid https://gitlab.com/bikedashboard/dashboard-api/-/blob/6ed262a8517e3aea01f8411efce8a41821ad2bc1/public_vehicles.py uit,  zodat we in ieder geval kunnen filteren op:

- Plaats
- Zones
- Vervoerstype (of gebeurt dat nu client side? dan niet)
- Aanbieder  (of gebeurt dat nu client side? dan niet)

![image](https://user-images.githubusercontent.com/899234/147950066-99c11f5f-953f-47e9-b435-019bab183917.png)

**Comment by sven4all** [comment]
Ok, je wil ook zones toevoegen? 

Dan moeten er meer endpoints publiek gaan worden anders kun je de zones ook niet ophalen.
