### ISSUE TITLE
add distance_in_meters to trips

### ISSUE THREAD

**Issue by sven4all** [Stichting-CROW/dashboarddeelmobiliteit-app#32]

**Comment by bartwr** [comment]
Sven heeft `distance_in_meters` toegevoegd aan het trips API end point:

https://gitlab.com/bikedashboard/dashboard-api/-/commit/0a95df10c54f8e6bb0fe6c214fc2cca3e50893fe

Het aantal meters wordt afgerond voor extra privacy. Op deze manier kun je niet de bestemming herleiden naar de herkomst en andersom.

https://gitlab.com/bikedashboard/dashboard-api/-/commit/6a98545fad4d8d71d980b65d6932b5acd55f64ff
