### ISSUE TITLE
Update site_menu_stats API end point

### ISSUE THREAD

**Issue by bartwr** [Stichting-CROW/dashboarddeelmobiliteit-app#35]
Update site_menu_stats API end point, zodat er gefilterd kan worden op:

- Voertuigtype
- Parkeerduur

![image](https://user-images.githubusercontent.com/899234/148562940-3f1ef2bd-2cdb-4996-a089-0b5a9b6ac059.png)

**Comment by bartwr** [comment]
Nieuwe stats endpoint: 

https://api.deelfietsdashboard.nl/dashboard-api/v2/park_events/stats?timestamp=2022-01-19T23:00:00Z&operators=cykl,flickbike,donkey,mobike,htm,gosharing,check,felyx,deelfietsnederland,keobike,lime,baqme,cargoroo,uwdeelfiets,hely,tier&zone_ids=34234

De volgorde van de array is de volgorde van de blobjes, dus:
- eerste waarde <1 uur
- tweede > 1 uur
- < 24 uur
- enz.

**Comment by bartwr** [comment]
Twee verzoeken ter verbetering van het end point:

1. Maak een publiek end point? Dan kunnen we deze stats ook tonen op de publieke site.
2. Als zones geselecteerd zijn, voeg dan ook de plaats toe. Niet alleen 'Kralingen' en 'Crooswijk', maar ook 'Rotterdam' in de dataset (liefst als eerst)

@sven4all

**Comment by sven4all** [comment]
Zeker over 2? Want als je die zones selecteert moeten ze sowieso altijd binnen een gemeente zijn. Dus dan krijg je voor elke zone er nog een keer de plaatsnaam voor.

**Comment by sven4all** [comment]
En nog een kleine suggestie, het zou ook mooi zijn om de stats van gemeente altijd boven aan te zetten (net als op het oude dashboard).

**Comment by sven4all** [comment]
Publiek doen we voorlopig niet, staat al wel klaar om gemerged te worden.
