### ISSUE TITLE
BUG: Fatale Invalid Date Exception na periodeselectie?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/dashboarddeelmobiliteit-app#38]
Om te reproduceren:

1. Log in
2. Ga naar tabblad Ontwikkeling. 
3. Selecteer gebied: Leeuwarden.
4. Selecteer periode: afgelopen 12 maanden
5. Selecteer weergave: maand
6. Selecteer tabblad: Verhuringen.

Verwachte resultaat:  
De inhoud van de pagina verhuringen over de geselecteerde gebied en periode.

Daadwerkelijk resultaat:  
Leeg scherm, met in console `Uncaught Error: Invalid date: Invalid Date` vanuitin de React code, uit DateTimeInput.js.

Een pagina-refresh, incl. cache wissen, laat nog steeds een leeg scherm zien. Met in console dezelfde melding.

Het wissen van Local Storage biedt wel soelaas.

**Comment by bartwr** [comment]
Vergelijkbare fout is: witte pagina na navigeren naar "Verhuringen"

Stappen om te reproduceren:
- Leeg je localStorage 
- Ga naar Aanbod-scherm
- Stel een stad in
- Ga naar Verhuringen-scherm

Verwacht resultaat:
- De kaart is zichtbaar.

Werkelijk resultaat:
- Een witte pagina verschijnt
- De fout zoals in onderstaand screenshots is zichtbaar in de console

Screenshot:

![image](https://user-images.githubusercontent.com/899234/149598229-65aedb79-964c-47fa-a7ed-007105b1b349.png)
