### ISSUE TITLE
Update mailtekst 'stel je wachtwoord in'

### ISSUE THREAD

**Issue by bartwr** [Stichting-CROW/dashboarddeelmobiliteit-app#44]
Wachtwoord herstellen met juist mailadres heeft verwijzing naar deelfietsdahbord

> Via onderstaande link kun je een nieuw wachtwoord instellen voor het Deelfiets Dashboard. Deze link blijft 24 uur geldig.
> 
> Klik hier om een nieuwe password in te stellen
> 
> Met vriendelijke groet,
> 
> Het Deelfiets-dashboard team

____

DO:

- [x] Deelfietsdashboard -> Dashboard Deelmobiliteit
- [x] Link naar dashboarddeelmobiliteit.nl/... voor instellen wachtwoord

**Comment by sven4all** [comment]
Aangepast, code op de website moet nog wel aangepast worden om dit te ondersteunen.
