### ISSUE TITLE
Als je uitgelogd bent blijven data nog wel zichtbaar tot je ververst

### ISSUE THREAD

**Issue by bartwr** [Stichting-CROW/dashboarddeelmobiliteit-app#45]
^

**Comment by mosbuma** [comment]
kan deze niet reproduceren: getest
- uitloggen -> crash -> fixed
- aanbodpagina selecteren -> uitloggen -> laadt data uit publieke API
- verhuringen pagina selecteren -> uitloggen  -> laadt data uit publieke API

**Comment by bartwr** [comment]
Dit is al een tijd geleden gefixt. => Closed.
