### ISSUE TITLE
Test app ingelogd als gemeente

### ISSUE THREAD

**Issue by bartwr** [Stichting-CROW/dashboarddeelmobiliteit-app#53]
^

**Comment by sven4all** [comment]
Werkt goed, alleen een probleem tegengekomen dat iedereen de downloadknop te zien krijgt (werkt overigens niet als je geen rechten hebt), ticket gemaakt om dit op te lossen.

**Comment by bartwr** [comment]
Tested => Works.

(Download button for downloading raw data is only shown if user rights are OK)
