### ISSUE TITLE
Voertuigicoontjes op HiDPI (retina)-schermen niet scherp

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/dashboarddeelmobiliteit-app#71]
Stappen:

1. Browse de beschikbare voertuigenkaart op een HiDPI-scherm, zoals de iPad die ik heb.
2. Selecteer de voertuigenlaag.

Verwacht:

1. De achtergrondkaart scherp en de voertuigbolletjes eveneens.

Feitelijk:

1. De achtergrondkaart is scherp, maar de voertuigbolletjes zijn onscherp.

Assignees:
Labels: bug

https://github.com/Stichting-CROW/dashboarddeelmobiliteit-app/blob/642b16c701d1bafdaed00cd69d10b24a68b02772/src/components/Map/vehicle_marker.js#L87-L103

**Comment by sven4all** [comment]
We gaan kijken of we er iets mee kunnen.

**Comment by sven4all** [comment]
Opgelost https://github.com/Stichting-CROW/dashboarddeelmobiliteit-app/commit/88268ccbf9883608a8e4e864e467ffff0a3f7e91 

Bart doet straks ook nog even een update van de plaatjes in het "lagen" menu, dan hebben we dat ook super scherp.

Als het live is laten we het je weten.

**Comment by redmer** [comment]
Sowieso mooi dat het ook werk op mobiele apparaten, dan sluit ik #72 👍

**Comment by bartwr** [comment]
Staat live => Closed.
