### ISSUE TITLE
Jump staat in Ontwikkeling-grafiek, ook als niet-geselecteerd

### ISSUE THREAD

**Issue by bartwr** [Stichting-CROW/dashboarddeelmobiliteit-app#78]
![image](https://user-images.githubusercontent.com/899234/151232096-8d878e7e-655a-46bd-8df6-3301d74a38db.png)

**Comment by mosbuma** [comment]
jump wordt niet meegegeven als aanbieder bij het opvragen van de metadata, komt daarom niet voor in het filter (ook toevoegen bij de hardgecodeerde constanten in poll-api/metadataAccesControlList.js#18)
